version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - POSTGRES_DB=devops_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - frontend-net
      - backend-net
    labels:
      project: "90days-devops"
      role: "frontend-api"

  db:
    image: docker.io/library/postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=devops_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d devops_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net
    labels:
      project: "90days-devops"
      role: "database"

  redis:
    image: docker.io/library/redis:7-alpine
    networks:
      - backend-net
    labels:
      project: "90days-devops"
      role: "cache"

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge

volumes:
  postgres_data:
